# Generated by Django 5.0.6 on 2024-05-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page_members_app', '0002_post_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
